spring:
  application:
    name: BookManagement

  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/library
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: user
      password: password
